on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
      # JDK 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      # Gradle 권한 
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      # Gradle Build
      - name: Build .jar file with Gradle
        run: ./gradlew clean bootJar
      # 빌드된 .jar 파일을 EC2로 복사
      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "build/libs/*.jar"
          target: "/home/${{ secrets.EC2_USER }}/poor-to-rich-server"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # AWS 배포
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd poor-to-rich-server
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker-compose build
            sudo docker-compose up -d
